### PR TITLE
Add in dialer_experience.xml to fix google phone bitching at us

### PR DESCRIPTION
**Pull request by anirudhgupta109**

### CODE REVIEW

**Comment by krasCGQ** [comment]
@anirudhgupta109 You yourself is b*tch 😂

**Comment by ghost** [comment]
@krasCGQ Lmao

**Comment by anirudhgupta109** [comment]
@krasCGQ Blame original commit-er for the language 😂😂

**Comment by Anandnv** [comment]
ani is on fire

**Pull request merged**
